--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1
-- Dumped by pg_dump version 16.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Cliente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Cliente" (
    "Id" integer NOT NULL,
    "Nome" text NOT NULL,
    "CPF" text NOT NULL,
    "Email" text NOT NULL,
    "Telefone" text NOT NULL,
    "Endereco" text NOT NULL,
    "IdVeiculo" integer
);


ALTER TABLE public."Cliente" OWNER TO postgres;

--
-- Name: Cliente_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Cliente" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Cliente_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Funcionario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Funcionario" (
    "Id" integer NOT NULL,
    "Nome" text NOT NULL,
    "Cargo" text NOT NULL
);


ALTER TABLE public."Funcionario" OWNER TO postgres;

--
-- Name: Funcionario_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Funcionario" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Funcionario_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: OrdemServico; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."OrdemServico" (
    "Id" integer NOT NULL,
    "IdCliente" integer NOT NULL,
    "IdFuncionarioResponsavel" integer NOT NULL,
    "DescricaoServico" text NOT NULL,
    "ValorTotal" numeric(10,2) NOT NULL,
    "DtInicioServico" timestamp with time zone NOT NULL,
    "DtFimServico" timestamp with time zone NOT NULL
);


ALTER TABLE public."OrdemServico" OWNER TO postgres;

--
-- Name: OrdemServicoItens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."OrdemServicoItens" (
    "Id" integer NOT NULL,
    "IdOrdemServico" integer NOT NULL,
    "IdProduto" integer NOT NULL,
    "Quantidade" integer NOT NULL,
    "ValorTotal" numeric(10,2) NOT NULL
);


ALTER TABLE public."OrdemServicoItens" OWNER TO postgres;

--
-- Name: OrdemServicoItens_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."OrdemServicoItens" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."OrdemServicoItens_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: OrdemServico_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."OrdemServico" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."OrdemServico_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Produto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Produto" (
    "Id" integer NOT NULL,
    "Nome" text NOT NULL,
    "Marca" text NOT NULL,
    "Preco" numeric(10,2) NOT NULL,
    "Quantidade" numeric(10,2) NOT NULL
);


ALTER TABLE public."Produto" OWNER TO postgres;

--
-- Name: Produto_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Produto" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Produto_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Veiculo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Veiculo" (
    "Id" integer NOT NULL,
    "Nome" text NOT NULL,
    "Placa" text NOT NULL,
    "Ano" text NOT NULL,
    "IdCliente" integer NOT NULL
);


ALTER TABLE public."Veiculo" OWNER TO postgres;

--
-- Name: Veiculo_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Veiculo" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Veiculo_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: Cliente; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Cliente" ("Id", "Nome", "CPF", "Email", "Telefone", "Endereco", "IdVeiculo") FROM stdin;
1	Osvaldo	053.108.847-26	osvaldoclaudionovaes@ficopola.net	(98) 98843-7643	Rua Eurípedes Chaves, 154, Anil -  São Luís (MA)	1
\.


--
-- Data for Name: Funcionario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Funcionario" ("Id", "Nome", "Cargo") FROM stdin;
1	Kaique	Mecânico
\.


--
-- Data for Name: OrdemServico; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."OrdemServico" ("Id", "IdCliente", "IdFuncionarioResponsavel", "DescricaoServico", "ValorTotal", "DtInicioServico", "DtFimServico") FROM stdin;
4	1	1	teste	121.98	2023-12-06 12:03:48-03	2024-01-19 11:54:00-03
\.


--
-- Data for Name: OrdemServicoItens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."OrdemServicoItens" ("Id", "IdOrdemServico", "IdProduto", "Quantidade", "ValorTotal") FROM stdin;
4	4	4	1	50.00
5	4	5	2	71.98
\.


--
-- Data for Name: Produto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Produto" ("Id", "Nome", "Marca", "Preco", "Quantidade") FROM stdin;
4	Óleo de Motor 5W-30	Castrol	50.00	5.00
5	Filtro de Ar Esportivo	K&N	35.99	30.00
6	Jogo de Velas de Ignição	NGK	25.50	30.00
\.


--
-- Data for Name: Veiculo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Veiculo" ("Id", "Nome", "Placa", "Ano", "IdCliente") FROM stdin;
1	Fiat - Palio Celebration 1.0 Fire Flex 8V 2p	JPQ-7362	2007	1
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20231206142817_InitialCreate	7.0.0
\.


--
-- Name: Cliente_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Cliente_Id_seq"', 1, true);


--
-- Name: Funcionario_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Funcionario_Id_seq"', 1, true);


--
-- Name: OrdemServicoItens_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."OrdemServicoItens_Id_seq"', 36, true);


--
-- Name: OrdemServico_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."OrdemServico_Id_seq"', 36, true);


--
-- Name: Produto_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Produto_Id_seq"', 6, true);


--
-- Name: Veiculo_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Veiculo_Id_seq"', 1, true);


--
-- Name: Cliente PK_Cliente; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Cliente"
    ADD CONSTRAINT "PK_Cliente" PRIMARY KEY ("Id");


--
-- Name: Funcionario PK_Funcionario; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Funcionario"
    ADD CONSTRAINT "PK_Funcionario" PRIMARY KEY ("Id");


--
-- Name: OrdemServico PK_OrdemServico; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrdemServico"
    ADD CONSTRAINT "PK_OrdemServico" PRIMARY KEY ("Id");


--
-- Name: OrdemServicoItens PK_OrdemServicoItens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrdemServicoItens"
    ADD CONSTRAINT "PK_OrdemServicoItens" PRIMARY KEY ("Id");


--
-- Name: Produto PK_Produto; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Produto"
    ADD CONSTRAINT "PK_Produto" PRIMARY KEY ("Id");


--
-- Name: Veiculo PK_Veiculo; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Veiculo"
    ADD CONSTRAINT "PK_Veiculo" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Veiculo_IdCliente; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Veiculo_IdCliente" ON public."Veiculo" USING btree ("IdCliente");


--
-- Name: Veiculo FK_Veiculo_Cliente_IdCliente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Veiculo"
    ADD CONSTRAINT "FK_Veiculo_Cliente_IdCliente" FOREIGN KEY ("IdCliente") REFERENCES public."Cliente"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

